### ISSUE TITLE
Create  a social media bar

### ISSUE THREAD

**Issue by bruno-keiko** [bruno-keiko/Restaurant-app#5]
**To-do list**

- [ ] Create a SocialMediaBar component in the atoms folder
- [ ] It should receive icons list props `socialMedias` with icon address and href
- [ ] It should receive a  `size` attribute (small, medium, large)
- [ ] It should match to [UIX](https://www.figma.com/design/xiAbsYNAyBYPH5pfPUkIEX/Restaurant-website-template-(Community)?node-id=42-834&t=nwlxPF6F2BQXmVMW-0) design
