### ISSUE TITLE
Create a MenuItem component

### ISSUE THREAD

**Issue by bruno-keiko** [bruno-keiko/Restaurant-app#8]
**To-do list**

- [x] Create a MenuItem component in the atoms folder
- [x] It should receive `name`, `ingredients`, and `price`
- [x] It should match with UIX [design](https://www.figma.com/design/xiAbsYNAyBYPH5pfPUkIEX/Restaurant-website-template-(Community)?node-id=1-3&t=UF4hHXSlrHt7PIki-0)

![image](https://github.com/user-attachments/assets/ef113988-bfee-42f7-b26f-679ec37bf8db)

**Comment by Hudayberdiev2000** [comment]
i will take this one
