### ISSUE TITLE
Create a SpecialMealCard component

### ISSUE THREAD

**Issue by bruno-keiko** [bruno-keiko/Restaurant-app#9]
**To-do list**

- [ ] Create a SpecialMealCard component in the atoms folder
- [ ] It should receive `image` and `name` props
- [ ] It should be matched with our UIX [design](https://www.figma.com/design/xiAbsYNAyBYPH5pfPUkIEX/Restaurant-website-template-(Community)?node-id=1-3&t=UF4hHXSlrHt7PIki-0)

**Comment by Hudayberdiev2000** [comment]
I will take this issue.
